### ISSUE TITLE
Can I run one test at a time?

### ISSUE THREAD

**Issue by parslaythemechanic** [UPB-FILS-ALF/questions#90]
I am trying to find the problem in my code as each test returns null, but I cannot add debugging snippets as they do not show when I run all the test via gitpush, how can I print in the console the checks I perform?

**Comment by mihaicostin34** [comment]
Yes, you can. Here are the steps:
1. Open you project either in codespaces or locally
2. In the terminal, run the command:
 ```
git clone --branch Updated2024 --single-branch https://github.com/UPB-FILS-ALF/devoir-3-tests.git
```
This will clone the tests repository into your project. Make sure you do not push this along with the changes and that you do not push any changes to the test results repository!

3. Find a test you want to run, then look for it in the `.github/classroom/autograding.json` file. For example, if I want to run the `1_value_empty` test, I would find its associated JSON:
```
{
        "name": "1_value_empty",
        "setup": "",
        "run": "cd devoir-3-tests/ && ./run.sh 1_value/empty.alf",
        "input": "",
        "output": "",
        "comparison": "exact",
        "timeout": 10,
        "points": 10
}
```
Then, take the command written in the `run` field and run it inside your terminal. This will run that test and give you the exact output, the same way it happens when the automated tests run.
